### ISSUE TITLE
[PE-D][Tester E] Unexpected behaviour in parsing of find_student command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W13-4/tp#193]
![image.png](https://raw.githubusercontent.com/ryan-txn/ped/main/files/e116b226-0b52-4f86-bfa3-a6d1ffe5cb2f.png)
adding extra i/ in name string causes the section to be read as an identity number. Additionally causes unexpected usage of command where input can be in reverse order.

![image.png](https://raw.githubusercontent.com/ryan-txn/ped/main/files/19f94337-3210-45f1-9503-c717b4dac88f.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ryan-txn/ped#9

**Comment by RCPilot1604** [comment]
For the case `i/A1234567X n/John Doei/A1234567X` the reason why the command goes through is twofold: 
1. find_student command accepts either n/NAME, i/MATRIC_NUMBER parameter or **both**
2. In the case of the malformed parameter `n/John Doei/A1234567X`, the n/ parameter matches `John` while `Doei/A1234567X` is dropped due to failing the regex expression

Therefore either 
1. i/A1234567X
2. n/John 
Allows the command to succeed. 

To test this, try
`find_student n/John Doei/A1234567X`
and 
`find_student i/A1234567X`
separately 
Both should succeed. On the contrary the following fails: 
```
find_student n/Johni/A1234567X
-------------------------   Error   -------------------------
No students with name Johni/A1234567X found
-------------------------------------------------------------
```
This explains the second screenshot as well.
